(() => {
  const applyImpactEnglish = () => {
    if (document.body.dataset.page !== 'impact.html' || document.body.dataset.lang !== 'en') return;

    const setHTML = (selector, html) => {
      const el = document.querySelector(selector);
      if (el) el.innerHTML = html;
    };

    document.title = 'Impact on Long-Distance Rail | Netherlands Train System';
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.setAttribute('content', 'How ERTMS/ETCS affects long-distance rail and legacy-fleet retrofit in the Netherlands.');
    const skip = document.querySelector('.skip-link');
    if (skip) skip.textContent = 'Skip to content';

    setHTML('.page-hero .page-hero-inner', `<div class="reveal visible"><div class="eyebrow"><span class="eyebrow-dot"></span> Chapter 04.2</div><h1>Direct impact on <span style="color:#003082">long-distance rail services</span></h1><p class="hero-copy">ETCS can improve train supervision and European interoperability, but migration affects much more than signalling: driving cabs, rolling stock, workshops and the number of trains available for daily service all have to adapt.</p></div><div class="page-badge glass-card reveal visible"><div class="big">Train + Track + People</div><p>The impact extends well beyond trackside signalling.</p></div>`);

    setHTML('#effects', `<div class="kicker">Impact snapshot</div><h2>When ETCS arrives, more than the trackside system changes</h2><p class="impact-lead">For long-distance rail, the main effects appear at the same time: safety supervision, cross-border operation, the driver’s cab, rolling-stock readiness and fleet availability while trains are being converted.</p>
      <div class="impact-snapshot" aria-label="Key impact facts"><div class="snapshot-item"><span>01</span><strong>6 areas</strong><small>From safety to rolling-stock availability</small></div><div class="snapshot-item"><span>02</span><strong>176 VIRM</strong><small>Trainsets in the ERTMS contract announced by NS in 2022</small></div><div class="snapshot-item"><span>03</span><strong>ATB + ETCS</strong><small>Converted trains may still need the legacy system during migration</small></div></div>
      <div class="impact-grid impact-grid-modern"><div class="impact-card glass-card"><div class="num">01</div><h3>More detailed safety supervision</h3><p>ETCS continuously checks speed, movement authority and braking, and can intervene when a train approaches an unsafe limit.</p></div><div class="impact-card glass-card"><div class="num">02</div><h3>Easier cross-border operation in the long term</h3><p>A common standard can reduce dependence on several national train-protection systems onboard international trains.</p></div><div class="impact-card glass-card"><div class="num">03</div><h3>More precise network management</h3><p>Digital information can support more precise train spacing, although real capacity still depends on infrastructure and timetables.</p></div><div class="impact-card glass-card"><div class="num">04</div><h3>The cab changes how drivers work</h3><p>Drivers rely more on the DMI and need to learn ETCS modes, transitions and procedures for degraded situations.</p></div><div class="impact-card glass-card"><div class="num">05</div><h3>Legacy trains require modification</h3><p>New computers, displays, radio equipment, antennas, sensors and cabling must be safely integrated with the train’s existing systems.</p></div><div class="impact-card glass-card"><div class="num">06</div><h3>Fleet availability can temporarily fall</h3><p>Vehicles in workshops for installation and testing cannot operate normally, so conversion slots and spare trains must be carefully planned.</p></div></div>`);

    setHTML('#retrofit', `<div class="kicker">Legacy Fleet Retrofit</div><h2>Older trains were not built with an empty space waiting for ETCS</h2>
      <div class="retrofit-showcase"><figure class="impact-media impact-media-virm"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/VIRM%20train%20dutch%20railways%20The%20Hague%20Centraal%20station.JPG?width=1600" alt="NS VIRM double-deck train at Den Haag Centraal" loading="lazy"><figcaption><strong>VIRM</strong><span>A legacy fleet receiving ERTMS after entering service</span></figcaption></figure><div class="retrofit-copy"><span class="impact-label">WHY RETROFIT IS HARD</span><h3>It is much more than adding one computer box</h3><p>Legacy trains were designed before ETCS became the main European standard. They may not have spare space, electrical interfaces, communications links or software architecture prepared for the new equipment. Engineers therefore have to make modern safety technology work reliably with systems designed years earlier.</p><div class="retrofit-mini-facts"><span>OBU / DMI</span><span>Radio &amp; antenna</span><span>Braking interface</span><span>New cabling</span></div></div></div>
      <div class="retrofit-points"><article class="retrofit-point"><span>SPACE</span><div><h3>Installation space is limited</h3><p>New equipment has to fit into a train already full of existing systems, sometimes requiring relocation or structural changes.</p></div></article><article class="retrofit-point"><span>ELEC</span><div><h3>Electrical and data systems must communicate</h3><p>ETCS interfaces with power, braking, speed measurement and train control, and those interfaces differ between fleets.</p></div></article><article class="retrofit-point"><span>COST</span><div><h3>Cost is more than the hardware price</h3><p>Prototype engineering, wiring, software, testing and safety authorisation all add to the total retrofit cost.</p></div></article><article class="retrofit-point"><span>TIME</span><div><h3>Trains need workshop downtime</h3><p>Installation and validation take time. If too many trains enter workshops together, the available service fleet can be squeezed.</p></div></article></div>
      <div class="transition-strip"><div><span>STM-ATB</span><strong>ETCS-equipped trains still need to run over ATB routes</strong><p>Because the network does not migrate everywhere at once, the same train may need to support both the new and legacy systems.</p></div><div><span>AUTHORISATION</span><strong>Safety must be demonstrated after modification</strong><p>New equipment has to pass verification, testing and the relevant authorisation process for the vehicle’s intended area of use.</p></div></div>`);

    setHTML('#virm-case', `<div class="kicker">Dutch case study</div><h2>VIRM shows the physical scale of a retrofit</h2><div class="virm-story"><figure class="impact-media impact-media-cab"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/NS%20VIRM%20Cabine%20Amersfoort.jpg?width=1600" alt="Driver cab of an NS VIRM train" loading="lazy"><figcaption><strong>VIRM cab</strong><span>The existing workspace has to accommodate new ETCS interfaces and equipment</span></figcaption></figure><div class="virm-story-copy"><span class="impact-label">CASE STUDY</span><h3>From a train designed in the ATB era to one that must work with ETCS</h3><p>NS describes the VIRM programme as adding ETCS computers, communications equipment and a driver display while adapting the train’s existing systems and cab environment to support the new technology.</p><div class="virm-metrics"><div><strong>176</strong><span>VIRM trainsets in the contract announced in 2022</span></div><div><strong>≈500 kg</strong><span>New cabling used by Programma ERTMS to illustrate the scale of VIRM work in 2026</span></div><div><strong>STM-ATB</strong><span>Allows an ETCS-equipped train to continue interpreting ATB during migration</span></div></div></div></div>`);

    setHTML('#fleet-compare', `<div class="kicker">Old fleet × New fleet</div><h2>Legacy and newer trains start from different positions</h2><div class="fleet-visual-compare"><div class="fleet-side legacy-side"><div class="fleet-side-head"><span>LEGACY</span><strong>VIRM / SLT / FLIRT</strong></div><p>These fleets require onboard installation or modification and integration with their existing architecture, so engineering and testing differ by vehicle series.</p><div class="fleet-tags"><span>New installation</span><span>New cabling</span><span>Fleet-specific testing</span></div></div><figure class="impact-media impact-media-icng"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/NS%20ICNG%20at%20Amsterdam%20Central%20Station%20in%202023.jpg?width=1600" alt="NS ICNG trains at Amsterdam Centraal" loading="lazy"><figcaption><strong>ICNG</strong><span>A newer fleet that NS says already has ERTMS onboard</span></figcaption></figure><div class="fleet-side newer-side"><div class="fleet-side-head"><span>NEWER</span><strong>SNG / ICNG</strong></div><p>Newer trains were prepared for ERTMS from the outset to a greater degree, so work focuses more on software and system-version upgrades than a complete first-time retrofit.</p><div class="fleet-tags"><span>Better prepared</span><span>Software focus</span><span>Less retrofit work</span></div></div></div>`);

    setHTML('#longdistance', `<div class="kicker">Long-distance services</div><h2>Why long-distance trains are affected so directly</h2><div class="longdistance-layout"><p>Long-distance trains cross more control areas and usually work intensively for long periods. International services also cross borders and encounter several signalling systems, making onboard readiness especially important.</p><div class="longdistance-points"><div><strong>01</strong><span>They must be ready for several systems and sometimes several countries.</span></div><div><strong>02</strong><span>Workshop time is limited because long-distance fleets are heavily used.</span></div><div><strong>03</strong><span>A fault on one trainset can affect a chain of long-distance services.</span></div></div></div>`);

    setHTML('#balance', `<div class="kicker">Balanced view</div><h2>Today’s migration burden supports a more capable long-term system</h2><div class="balance-board"><div class="balance-side migration-side"><span>During migration</span><ul><li>Legacy trains may need both ATB and ETCS</li><li>Some vehicles leave service for retrofit and testing</li><li>Staff learn new displays and operating procedures</li><li>Old and new hardware/software must be integrated safely</li></ul></div><div class="balance-arrow" aria-hidden="true">→</div><div class="balance-side mature-side"><span>When the system is mature</span><ul><li>Less dependence on multiple national protection systems</li><li>ETCS-ready trains can use more of the common European standard</li><li>More standardised safety information in the cab</li><li>A stronger technical foundation for future digital rail</li></ul></div></div><div class="reference-cta glass-card"><div><span>Verify the evidence</span><strong>All Chapter 04.2 references are collected in the Reference Library</strong></div><a href="other.html?lang=en#ref-impact">Open references <span aria-hidden="true">→</span></a></div>`);

    setHTML('.aside', `<p class="aside-title">On this page</p><a href="#effects">Impact overview</a><a href="#retrofit">Legacy fleet retrofit</a><a href="#virm-case">VIRM case study</a><a href="#fleet-compare">Legacy vs newer fleet</a><a href="#longdistance">Long-distance services</a><a href="#balance">Migration vs long term</a><a href="other.html?lang=en#ref-impact">References</a>`);
  };

  if (document.readyState === 'complete') applyImpactEnglish();
  else window.addEventListener('load', applyImpactEnglish, { once: true });
})();
