(() => {
  const applyProblemsEnglish = () => {
    if (document.body.dataset.page !== 'problems.html' || document.body.dataset.lang !== 'en') return;

    const setHTML = (selector, html) => {
      const el = document.querySelector(selector);
      if (el) el.innerHTML = html;
    };

    document.title = 'Problems and Challenges | Netherlands Train System';
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.setAttribute('content', 'Problems and challenges in the Dutch transition from ATB to ERTMS/ETCS, including schedule delays, cost pressure, reliability and freight operators.');

    setHTML('.page-hero .page-hero-inner', `<div class="reveal visible"><div class="eyebrow"><span class="eyebrow-dot"></span> Chapter 03.2 • Updated 2026</div><h1>Problems and challenges <span style="color:#ae1c28">during the migration</span></h1><p class="hero-copy">Moving from ATB to ERTMS/ETCS is not a single equipment replacement. Trains, infrastructure, control systems, software, staff and many operators all have to become ready to work together. A delay in one part can therefore affect the wider programme.</p></div><div class="page-badge glass-card reveal visible"><div class="big">1 railway · many systems</div><p>The main challenge is getting every part ready at the same time.</p></div>`);

    setHTML('#overview', `<div class="kicker">Challenge map</div><h2>The main problems do not come from one cause</h2><p class="problem-lead">Programme progress reports and Dutch government documents show that the difficulty of ERTMS comes from several connected issues: developing central systems, converting trains, keeping ATB available during migration, training staff and dealing with incidents in a more digital railway.</p><div class="problem-snapshot"><div class="problem-snapshot-card"><span>TIME</span><strong>Schedules move</strong><small>Some systems take longer to develop and test than expected.</small></div><div class="problem-snapshot-card"><span>€</span><strong>Time creates cost</strong><small>A slower migration means investing in legacy ATB and new ERTMS at the same time for longer.</small></div><div class="problem-snapshot-card"><span>R</span><strong>Reliability</strong><small>Train, track, radio, software and incident handling need to be managed as one chain.</small></div><div class="problem-snapshot-card"><span>F</span><strong>Freight</strong><small>Freight operators must convert locomotives, carry part of the cost and keep enough vehicles available during retrofit.</small></div></div>`);

    setHTML('#delay', `<div class="kicker">Why the plan slipped</div><h2>Why the transition is later than the earlier plan</h2><p>The main cause is not simply slow construction. The earlier plan depended on several systems that still needed development and full system-level validation. In 2024 the programme acknowledged that the existing approach and schedule were no longer sufficiently realistic. The migration was therefore restructured into smaller <strong>Tranches</strong> so risks could be controlled and lessons learned before moving to more complex areas.</p><div class="delay-grid"><article class="delay-card glass-card"><span>01</span><h3>The Central Safety System needs more development time</h3><p>The CSS is a key system linking information from trains and infrastructure. Programme reporting in 2025 said its schedule was moving, while new requirements from European regulation created additional development work.</p></article><article class="delay-card glass-card"><span>02</span><h3>STM ATB-NG proved harder than expected</h3><p>ERTMS trains operating over ATB-NG territory need a translation module. Development for Northern Lines rolling stock has been more complex and expensive than expected; the government reported a €6 million setback in the first half of 2025.</p></article><article class="delay-card glass-card"><span>03</span><h3>The whole railway chain must be tested</h3><p>Passing component tests is not enough. Trains, trackside equipment, communications and software have to work together. A defect can require a software change, repeat testing and renewed approval.</p></article><article class="delay-card glass-card"><span>04</span><h3>The railway must keep operating during the work</h3><p>Installation and testing have to fit around normal passenger and freight services. Track possessions and test windows therefore need careful planning.</p></article></div><div class="problem-note"><strong>In simple terms:</strong> the delay is caused by interdependence. If the CSS, STM, rolling stock or system testing is not ready, the route cannot safely enter full ERTMS operation.</div>`);

    setHTML('#cost', `<div class="kicker">Cost impact</div><h2>Impact on cost</h2><p>The transition requires investment in onboard equipment, infrastructure, control systems, software, testing and staff training. At the same time, ATB must remain safe and maintainable until each area completes its migration. A longer transition therefore extends the period in which the Netherlands pays for both the legacy and new systems.</p><div class="cost-metrics"><div class="cost-metric"><small>Mid-2025</small><strong>€163m</strong><span>Budget tension reported for Tranche 1.</span></div><div class="cost-metric featured"><small>End-2025 · reported Apr 2026</small><strong>≈€219m</strong><span>Potential programme shortfall; the increase was almost entirely linked to price compensation not being fully allocated.</span></div><div class="cost-metric"><small>Risk picture</small><strong>≈€100m</strong><span>Additional risk estimate, mainly associated with the shifting Tranche 1 schedule.</span></div></div><div class="problem-note warning"><strong>Do not add these three figures together:</strong> they refer to different reporting dates and different concepts. Some represent a budget gap, while another represents risks that may or may not materialise.</div><p>The government also states that later delivery dates create extra legacy-system costs because ATB must be kept operational for longer. Keeping milestones on time is therefore one of the most effective ways to limit long-term programme costs.</p>`);

    setHTML('#dual', `<div class="kicker">Dual operation</div><h2>The period when ATB and ERTMS must coexist</h2><p>The Netherlands cannot convert its whole network in one day. Trains fitted with ERTMS must still operate on routes protected by ATB, meaning one train may need to support both old and new technology during migration.</p><div class="dual-bridge glass-card" aria-label="ATB STM and ETCS interoperability"><div class="dual-node legacy"><span>Legacy trackside system</span><strong>ATB</strong><small>Sends information using the national system</small></div><div class="dual-arrow" aria-hidden="true">→</div><div class="dual-node bridge"><span>Translator</span><strong>STM-ATB</strong><small>Converts ATB information for the onboard system</small></div><div class="dual-arrow" aria-hidden="true">→</div><div class="dual-node target"><span>New onboard system</span><strong>ERTMS / ETCS</strong><small>Uses the information for train supervision</small></div></div><p>The challenge is that hardware, software and vehicle configuration must remain compatible. A software or specification change in one subsystem can require checks and testing elsewhere.</p>`);

    setHTML('#reliability', `<div class="kicker">Reliability</div><h2>System reliability</h2><p><strong>Safety</strong> and <strong>service reliability</strong> are different. ETCS is designed to stop a train if the system cannot confirm safe movement, but a safe stop can still cause delay or strand a train. The programme therefore has to achieve both safe behaviour and reliable day-to-day operation with rapid incident recovery.</p><div class="reliability-layout"><div class="reliability-story glass-card"><span class="impact-label">REAL CASE</span><h3>The Aachen balise: a safe stop caused by an unreadable instruction</h3><p>During testing of Arriva's tri-country train, a balise near Aachen Hbf had been programmed incorrectly. The train could not interpret the instruction and automatically stopped for safety. After the software correction, the change still had to be tested and approved before service could begin.</p></div><div class="reliability-principles"><div><strong>Look at the whole chain</strong><span>An incident may come from rolling stock, infrastructure, radio, software or several interfaces together.</span></div><div><strong>Share data</strong><span>ProRail and operators are combining onboard and infrastructure data to identify causes more quickly.</span></div><div><strong>Control updates</strong><span>A software change can affect other subsystems, so configuration and testing need disciplined management.</span></div></div></div><div class="problem-note"><strong>Lesson from the Betuweroute:</strong> in 2025 the chain-management team worked with four freight operators to study service disruptions and the effect of system updates, building lessons for future ERTMS operations.</div>`);

    setHTML('#freight', `<div class="kicker">Freight operators</div><h2>Impact on rail freight operators</h2><p>Freight operators face a different challenge from many passenger fleets because locomotives often cross borders, work over many routes and may be owned by different companies. As European corridors migrate, locomotives using those routes need ETCS that meets the required system version.</p><div class="freight-panel"><div class="freight-main glass-card"><span class="impact-label">2025 SUPPORT SCHEME</span><h3>Public support exists, but operators still carry part of the cost</h3><p>From 2025 the Netherlands introduced a temporary support scheme for upgrading or retrofitting freight locomotives. The regulation explicitly notes that conversion is expensive and offers no immediate direct return, so support is intended to limit damage to rail freight competitiveness.</p><div class="freight-stats"><div><strong>185–205</strong><span>freight locomotives the 2025 scheme estimated could be supported for conversion</span></div><div><strong>2</strong><span>prototype locomotive developments that may receive support</span></div></div></div><div class="freight-side"><article><span>01</span><h3>Downtime removes earning capacity</h3><p>A locomotive in the workshop for ETCS installation and testing cannot operate normally, while temporary replacement locomotives can also be expensive.</p></article><article><span>02</span><h3>ATB and ETCS must both be supported</h3><p>Until the network migration is complete, many locomotives still need to work with both legacy and new systems.</p></article><article><span>03</span><h3>Costs affect competitiveness</h3><p>If conversion costs are passed through too heavily to customers, rail freight can become less competitive against other transport modes.</p></article></div></div>`);

    setHTML('#people-tech', `<div class="kicker">People · Operations · Digital</div><h2>People, daily operations and digital systems must change too</h2><div class="people-tech-grid"><article class="glass-card"><span>PEOPLE</span><h3>Staff need new competence</h3><p>Drivers, traffic controllers, maintainers and testers need training in new displays, rules and degraded-mode procedures. During migration, some staff need to understand both ATB and ERTMS.</p></article><article class="glass-card"><span>OPERATION</span><h3>Engineering work must coexist with the timetable</h3><p>Track possessions, balise installation, control-system changes and test runs all take place on a railway that still carries passengers and freight.</p></article><article class="glass-card"><span>DIGITAL</span><h3>Software and cybersecurity become more important</h3><p>ERTMS connects onboard, trackside, control and communication systems more closely. Software configuration, encrypted data and cybersecurity therefore become core operating requirements rather than optional extras.</p></article></div>`);

    setHTML('#conclusion', `<div class="kicker">What this means</div><h2>Why the Netherlands is now migrating step by step</h2><p>The evidence points to one conclusion: moving from ATB to ERTMS is a transformation of the whole railway system, not a normal equipment-installation project. The Tranche approach lets the sector solve problems in controlled areas first and carry those lessons into more complex corridors with multiple operators and international traffic.</p><a class="reference-jump" href="other.html?lang=en#ref-problems"><span>Check the sources for Chapter 03.2</span><strong>Reference Library →</strong></a>`);

    setHTML('.aside', `<p class="aside-title">On this page</p><a href="#overview">Challenge overview</a><a href="#delay">Why the plan slipped</a><a href="#cost">Cost impact</a><a href="#dual">ATB + ERTMS</a><a href="#reliability">Reliability</a><a href="#freight">Freight operators</a><a href="#people-tech">People and digital systems</a><a href="other.html?lang=en#ref-problems">References</a>`);
  };

  if (document.readyState === 'complete') applyProblemsEnglish();
  else window.addEventListener('load', applyProblemsEnglish, { once: true });
})();