(() => {
  const applyProblemsEnglish = () => {
    if (document.body.dataset.page !== 'problems.html' || document.body.dataset.lang !== 'en') return;

    const setHTML = (selector, html) => {
      const el = document.querySelector(selector);
      if (el) el.innerHTML = html;
    };

    document.title = 'Problems and Challenges | Netherlands Train System';
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.setAttribute('content', 'Problems in the Dutch transition from ATB to ERTMS/ETCS, including delay, cost, reliability and freight operators.');

    setHTML('.page-hero .page-hero-inner', `<div class="reveal visible"><div class="eyebrow"><span class="eyebrow-dot"></span> Chapter 03.2 • Updated 2026</div><h1>Problems and challenges <span style="color:#ae1c28">during the migration</span></h1><p class="hero-copy">Moving from ATB to ERTMS/ETCS changes trains, trackside systems, software and working practices at the same time. If one part is not ready, other parts may have to wait.</p></div><div class="page-badge glass-card reveal visible"><div class="big">1 railway · many systems</div><p>The hard part is getting everything ready and working together at the same time.</p></div>`);

    setHTML('#overview', `<div class="kicker">Challenge map</div><h2>Why this is harder than a normal equipment replacement</h2><p class="problem-lead">ERTMS changes many parts of the railway at once: equipment on trains, trackside systems, control centres, software and staff. At the same time, ATB must remain in service until each area is ready to switch. That creates several connected problems.</p><div class="problem-snapshot"><div class="problem-snapshot-card"><span>TIME</span><strong>It takes longer than expected</strong><small>Some key systems need more development and testing.</small></div><div class="problem-snapshot-card"><span>€</span><strong>Delay creates extra cost</strong><small>The railway has to support old ATB while investing in new ERTMS.</small></div><div class="problem-snapshot-card"><span>R</span><strong>It has to work every day</strong><small>The system must be safe without causing too many service interruptions.</small></div><div class="problem-snapshot-card"><span>F</span><strong>Freight is directly affected</strong><small>Locomotives need ETCS and may be unavailable during conversion.</small></div></div>`);

    setHTML('#delay', `<div class="kicker">Why the plan slipped</div><h2>Why the transition is later than the earlier plan</h2><p>The main reason is not simply slow construction. Several systems still needed development, testing and proof that they could work together. When the earlier schedule proved too ambitious, the Netherlands moved to smaller <strong>Tranches</strong>: solve problems in a controlled area first, then expand.</p><div class="delay-grid"><article class="delay-card glass-card"><span>01</span><h3>The central safety system needs more development</h3><p>The <strong>Central Safety System (CSS)</strong> is a key part of the link between trains and infrastructure. Some development has taken longer than expected and new European requirements added extra work.</p></article><article class="delay-card glass-card"><span>02</span><h3>The ATB-NG translator is harder than expected</h3><p><strong>STM ATB-NG</strong> works like a translator so an ERTMS train can still understand ATB-NG. Development for Northern Lines rolling stock proved more difficult and expensive than expected, with a reported €6 million setback in the first half of 2025.</p></article><article class="delay-card glass-card"><span>03</span><h3>Testing separate parts is not enough</h3><p>The train, trackside equipment, communications and software have to be tested together. One fault can mean a software change and another round of testing.</p></article><article class="delay-card glass-card"><span>04</span><h3>The railway still has to run every day</h3><p>Installation and testing must fit around passenger and freight services, so the railway cannot simply be closed whenever work is needed.</p></article></div><figure class="problem-media problem-media-wide"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Eurobalises%20Utrecht%20CS%20noordzijde%20sporen%2011-13.jpg?width=1600" alt="Eurobalises at Utrecht Centraal on the Amsterdam–Utrecht ERTMS route" loading="lazy"><figcaption><strong>Eurobalises at Utrecht Centraal</strong><span>Trackside equipment is only one part of the system. Trains, software and control systems still have to work together before full operation is possible.</span></figcaption></figure><div class="problem-note"><strong>In simple terms:</strong> if the CSS, STM, rolling stock or system testing is not ready, the route cannot enter full ERTMS operation.</div>`);

    setHTML('#cost', `<div class="kicker">Cost impact</div><h2>How delay affects cost</h2><p>During the migration the railway pays in two directions at once: building the new ERTMS system while keeping ATB safe and usable. The longer migration takes, the longer both systems need funding at the same time.</p><div class="cost-metrics"><div class="cost-metric"><small>Mid-2025</small><strong>€163m</strong><span>Budget tension reported for Tranche 1.</span></div><div class="cost-metric featured"><small>End-2025 · reported Apr 2026</small><strong>≈€219m</strong><span>Potential shortfall; the increase was almost entirely linked to price compensation not being fully allocated.</span></div><div class="cost-metric"><small>Additional risk</small><strong>≈€100m</strong><span>Risk estimate mainly linked to the delayed Tranche 1 schedule.</span></div></div><div class="problem-note warning"><strong>Do not add these figures together:</strong> they come from different reporting dates and describe different things. Some are budget gaps; another is a risk that may or may not occur.</div>`);

    setHTML('#dual', `<div class="kicker">Dual operation</div><h2>When ATB and ERTMS have to work side by side</h2><p>The Netherlands cannot switch the whole network at once. An ERTMS-equipped train may still need to run on ATB routes. <strong>STM-ATB</strong> acts as a translator, helping the new onboard system understand ATB information.</p><div class="dual-bridge glass-card" aria-label="ATB STM and ETCS interoperability"><div class="dual-node legacy"><span>Legacy trackside system</span><strong>ATB</strong><small>Sends information using the national system</small></div><div class="dual-arrow" aria-hidden="true">→</div><div class="dual-node bridge"><span>Translator</span><strong>STM-ATB</strong><small>Converts information for the train</small></div><div class="dual-arrow" aria-hidden="true">→</div><div class="dual-node target"><span>New onboard system</span><strong>ERTMS / ETCS</strong><small>Uses the data for safe supervision</small></div></div><p>The difficulty is that each train type has different hardware and software. A change in one part can therefore trigger checks and testing elsewhere.</p>`);

    setHTML('#reliability', `<div class="kicker">Reliability</div><h2>“Safe” and “reliable in daily service” are not the same thing</h2><p>ETCS is designed to stop a train when the system cannot confirm that movement is safe. That is correct from a safety point of view, but frequent safe stops would still create delays. The system therefore needs to be both safe and dependable in everyday operation.</p><div class="reliability-photo-layout"><figure class="problem-media problem-media-portrait"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Maastricht%20station%20-%20Drielandentrein%20%28LIMAX%29%20richting%20Li%C3%A8ge-Guillemins%20-%202024-08-14.jpg?width=1400" alt="Drielandentrein or LIMAX at Maastricht station" loading="lazy"><figcaption><strong>Drielandentrein / LIMAX</strong><span>A cross-border train linking the Netherlands, Belgium and Germany, where several systems have to coexist during migration.</span></figcaption></figure><div class="reliability-content"><div class="reliability-story glass-card"><span class="impact-label">REAL CASE</span><h3>An Aachen balise caused a safe automatic stop</h3><p>During testing of the tri-country train, a balise near Aachen Hbf had been configured incorrectly. The train could not interpret the instruction and stopped automatically. After the software correction, the change still had to be tested and approved again.</p></div><div class="reliability-principles"><div><strong>Look at the whole system</strong><span>The cause may be on the train, track, radio link, software or several places at once.</span></div><div><strong>Use data from train and track</strong><span>Combining both sides helps teams find the cause faster.</span></div><div><strong>Test again after changes</strong><span>A software update in one part can affect another subsystem.</span></div></div></div></div><div class="problem-note"><strong>Lesson from the Betuweroute:</strong> in 2025 the ERTMS team worked with four freight operators to analyse disruptions and software updates, building practical experience for future routes.</div>`);

    setHTML('#freight', `<div class="kicker">Freight operators</div><h2>Why freight operators feel the impact strongly</h2><p>Freight locomotives often run long distances, cross borders and work on many different routes. When those routes start requiring ETCS, operators have to upgrade locomotives even if the existing vehicles are still mechanically useful.</p><div class="freight-visual"><figure class="problem-media problem-media-freight"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Betuweroute%20189-095%20met%20containertrein%20%289429282350%29.jpg?width=1600" alt="Container freight train on the Betuweroute in the Netherlands" loading="lazy"><figcaption><strong>Freight trains cross national borders</strong><span>The Betuweroute links Rotterdam with Germany, so changes in train-control standards have direct cross-border consequences.</span></figcaption></figure><div class="freight-main glass-card"><span class="impact-label">2025 SUPPORT SCHEME</span><h3>Public support covers part of the cost, not all of it</h3><p>The Netherlands introduced temporary support for upgrading or retrofitting freight locomotives because ETCS conversion is expensive and locomotives are unavailable while the work is carried out.</p><div class="freight-stats"><div><strong>185–205</strong><span>locomotives the scheme estimated could be supported for conversion</span></div><div><strong>2</strong><span>prototype locomotive developments that may receive support</span></div></div></div></div><div class="freight-side freight-side-horizontal"><article><span>01</span><h3>Workshop time means no normal service</h3><p>A locomotive undergoing ETCS installation and testing cannot earn revenue normally, so spare or replacement vehicles may be needed.</p></article><article><span>02</span><h3>Legacy systems still matter</h3><p>Until migration is complete, some locomotives need to support both ATB and ETCS.</p></article><article><span>03</span><h3>Higher cost affects competition</h3><p>If conversion costs become too high, rail freight can become less competitive against other transport modes.</p></article></div>`);

    setHTML('#people-tech', `<div class="kicker">People · Operations · Digital</div><h2>New technology also means new skills and new ways of working</h2><div class="people-tech-grid"><article class="glass-card"><span>PEOPLE</span><h3>Staff need new training</h3><p>Drivers, controllers, technicians and testers need to learn new displays, rules and ways of dealing with faults.</p></article><article class="glass-card"><span>OPERATION</span><h3>Installation must fit around real trains</h3><p>Track closures, balise installation and test runs need to be planned so passenger and freight disruption stays as small as possible.</p></article><article class="glass-card"><span>DIGITAL</span><h3>Software and cybersecurity matter more</h3><p>As trains, track and control centres become more connected, software versions, data protection and cyber security become part of normal railway operations.</p></article></div>`);

    setHTML('#conclusion', `<div class="kicker">What this means</div><h2>Why the Netherlands is changing the system step by step</h2><p>ERTMS changes many parts of the railway at once. Starting in controlled areas allows the sector to find problems, fix them and learn before moving to more complex routes.</p><a class="reference-jump" href="other.html?lang=en#ref-problems"><span>Check Chapter 03.2 sources and image credits</span><strong>Reference Library →</strong></a>`);

    setHTML('.aside', `<p class="aside-title">On this page</p><a href="#overview">Overview</a><a href="#delay">Why the plan slipped</a><a href="#cost">Cost impact</a><a href="#dual">ATB + ERTMS</a><a href="#reliability">Reliability</a><a href="#freight">Freight operators</a><a href="#people-tech">People and digital systems</a><a href="other.html?lang=en#ref-problems">References</a>`);
  };

  if (document.readyState === 'complete') applyProblemsEnglish();
  else window.addEventListener('load', applyProblemsEnglish, { once: true });
})();