(() => {
  if (document.documentElement.lang !== 'en' || document.body.dataset.page !== 'summary.html') return;

  const setHTML = (selector, html) => {
    const el = document.querySelector(selector);
    if (el) el.innerHTML = html;
  };
  const setText = (selector, text) => {
    const el = document.querySelector(selector);
    if (el) el.textContent = text;
  };

  document.title = 'Conclusion | Netherlands Train System';
  const meta = document.querySelector('meta[name="description"]');
  if (meta) meta.setAttribute('content', 'Conclusion of the Dutch transition from ATB to ERTMS/ETCS, including the 2026 status, neighbouring-country lessons and long-distance rail impacts.');
  setText('.skip-link', 'Skip to content');

  setHTML('.page-hero .page-hero-inner', `<div class="reveal"><div class="eyebrow"><span class="eyebrow-dot"></span> Chapter 05</div><h1>Conclusion <span style="color:#003082">the transition from ATB to ERTMS/ETCS</span></h1><p class="hero-copy">The Dutch signalling transition is not simply a replacement of old equipment with new technology. Infrastructure, rolling stock, software, operating procedures and people all need to work together under a common European digital railway standard.</p></div><div class="page-badge glass-card reveal"><div class="big">ATB → ETCS</div><p>From a national train-protection system to a common European standard</p></div>`);

  setHTML('#overview', `<div class="kicker">5.1 • Overview</div><h2>Overview of the transition</h2><p><strong>ATB</strong> has played a major role in Dutch railway safety for decades and established an important protection layer across much of the main network. However, it is a national system designed before Europe developed a common signalling standard, which limits detailed speed supervision, cross-border interoperability and future digital development.</p><p><strong>ERTMS/ETCS</strong> is therefore not being introduced because ATB has suddenly stopped working. The Netherlands is moving toward a system that can supervise speed and braking more precisely, operate on a common European standard and provide a platform for more digital control, communication and automation in the future.</p><div class="info-grid"><div class="info-card glass-card"><div class="icon">ATB</div><h3>A legacy system that still matters</h3><p>ATB remains the main train-protection system on many routes while the migration is still under way.</p></div><div class="info-card glass-card"><div class="icon">L2</div><h3>ETCS Level 2</h3><p>The main direction of the current programme, using digital information and radio communication to supervise train movements.</p></div><div class="info-card glass-card"><div class="icon">01</div><h3>A whole-system change</h3><p>Trains, infrastructure, control systems, software, operating rules and training all need to change together.</p></div><div class="info-card glass-card"><div class="icon">EU</div><h3>A common European objective</h3><p>The long-term goal is to reduce dependence on many national train-protection systems and improve interoperability.</p></div></div>`);

  setHTML('#findings', `<div class="kicker">Key findings</div><h2>Key findings from the study</h2><div class="impact-grid"><div class="impact-card glass-card"><div class="num">01</div><h3>More detailed safety supervision</h3><p>ETCS continuously supervises speed and braking curves and can intervene when a train approaches an unsafe limit.</p></div><div class="impact-card glass-card"><div class="num">02</div><h3>Better long-term cross-border interoperability</h3><p>A common standard can reduce the need for international trains to depend on several national protection systems, although multiple systems remain necessary during migration.</p></div><div class="impact-card glass-card"><div class="num">03</div><h3>The main challenge is system integration</h3><p>Central systems, onboard equipment, infrastructure, software and staff readiness are tightly connected. A delay in one area can move the wider programme schedule.</p></div><div class="impact-card glass-card"><div class="num">04</div><h3>Staged deployment reduces risk</h3><p>The Tranche approach allows the Netherlands to begin in controlled areas, learn from real operations and then move into more complex parts of the network.</p></div></div>`);

  setHTML('#status', `<div class="kicker">Current position • 2026</div><h2>The Netherlands is still in transition</h2><p>The Netherlands already has operational ERTMS experience on important routes including the Betuweroute, HSL-Zuid, Hanzelijn and Amsterdam–Utrecht. Replacing ATB across the national network, however, is a much larger and more complex programme.</p><p>In 2026 the national programme is being delivered through a <strong>Tranche</strong> approach. Tranche 1 covers around <strong>419 km of infrastructure</strong>, with physical field work under way on Leeuwarden–Harlingen Haven while other areas remain in design, test preparation and system-readiness phases.</p><div class="callout"><strong>Important point:</strong> installing ERTMS equipment on part of a route does not mean that the Netherlands has completed the ATB-to-ETCS migration. Commissioning can only take place once rolling stock, infrastructure, control systems, staff and the safety-authorisation process are ready together.</div>`);

  setHTML('#comparison', `<div class="kicker">Neighbouring countries</div><h2>Lessons from Belgium and Germany</h2><p>Comparison with neighbouring countries shows that there is no single ETCS migration model that works for every railway. Network size, legacy systems, operator structure, rolling-stock readiness and investment policy differ considerably.</p><div class="country-grid"><div class="country-card glass-card"><div class="flag nl"></div><h3>Netherlands</h3><div class="metric">Tranche</div><p>Uses staged learning and testing before moving into more complex areas, with an emphasis on controlling whole-system risk.</p></div><div class="country-card glass-card"><div class="flag be"></div><h3>Belgium</h3><div class="metric">100%</div><p>Reached ETCS availability across the main network in December 2025, reflecting a sustained nationwide coverage strategy.</p></div><div class="country-card glass-card"><div class="flag de"></div><h3>Germany</h3><div class="metric">Corridors</div><p>Progresses through corridor and strategic-node projects while also modernising digital interlockings and other railway architecture, creating several layers of change at once.</p></div></div><div class="callout"><strong>Comparison caution:</strong> route kilometres, track kilometres and ETCS coverage percentages are not always measured in the same way between countries, so figures should always be read together with the definition used by the source.</div>`);

  setHTML('#impact', `<div class="kicker">Long-distance rail</div><h2>What this means for long-distance trains</h2><p>Passengers may not see ETCS as a visible piece of equipment, but its effects are reflected in how trains are supervised, how international services cross borders, how rolling stock is prepared and how efficiently the network can be used.</p><div class="info-grid"><div class="info-card glass-card"><div class="icon">S</div><h3>Safety</h3><p>More detailed speed and braking supervision provides an additional safety layer in train operation.</p></div><div class="info-card glass-card"><div class="icon">↔</div><h3>Cross-border</h3><p>A common standard is especially important for trains running between the Netherlands, Belgium and Germany.</p></div><div class="info-card glass-card"><div class="icon">C</div><h3>Capacity</h3><p>Digital train-control systems provide a foundation for more efficient headways and network use in the future.</p></div><div class="info-card glass-card"><div class="icon">T</div><h3>Transition burden</h3><p>In the short term, passengers can still be affected by possessions, testing and rolling-stock constraints during migration.</p></div></div>`);

  setHTML('#conclusion', `<div class="kicker">Conclusion</div><h2>Final conclusion</h2><p>The transition from ATB to ERTMS/ETCS is a long-term renewal of the safety and control foundation of the Dutch railway. The central issue is therefore not simply that one technology is newer than another, but whether trains, infrastructure, control systems and people can operate safely together under one common standard.</p><p>The experience of the Netherlands, Belgium and Germany demonstrates that ETCS is a shared European destination, while the path toward it differs by country. For the Netherlands, success will depend on managing complexity, testing in stages, preparing rolling stock and staff, and applying the lessons from the first Tranches effectively to later deployment areas.</p><div class="callout"><strong>In one sentence:</strong> ATB helped build the safety foundation of the Dutch railway in the past, while ERTMS/ETCS is the infrastructure intended to connect the Netherlands to a more digital and interoperable European railway future.</div><div class="source-list"><a class="source-link" href="other.html#sources"><span>Open the website reference library</span><span>→</span></a></div>`);

  setHTML('.aside', `<p class="aside-title">On this page</p><a href="#overview">Overview</a><a href="#findings">Key findings</a><a href="#status">2026 status</a><a href="#comparison">Three-country lessons</a><a href="#impact">Long-distance rail impact</a><a href="#conclusion">Final conclusion</a><a href="other.html#sources">References</a>`);
})();